create table tb_funcoes (id int8 generated by default as identity, funcao varchar(255), primary key (id));
create table tb_usuarios (id int8 generated by default as identity, email varchar(255), nome varchar(255), senha varchar(255), primary key (id));
create table tb_usuarios_funcoes (usuario_id int8 not null, funcao_id int8 not null, primary key (usuario_id, funcao_id));
alter table if exists tb_usuarios add constraint UK_hymsg6hpnk88xrsy9kdsuhur9 unique (email);
alter table if exists tb_usuarios_funcoes add constraint FK2lmpyk22s4woj6amfjse5i4j7 foreign key (funcao_id) references tb_funcoes;
alter table if exists tb_usuarios_funcoes add constraint FKdcxrg3p4jjlj61equj4ujq07 foreign key (usuario_id) references tb_usuarios;
