create table tb_trabalhadores (id int8 generated by default as identity, nome varchar(255), valor_por_dia float8, primary key (id));
create table tb_trabalhadores (id int8 generated by default as identity, nome varchar(255), valor_por_dia float8, primary key (id));
